//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TacoBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string AddressDialog_Confirm {
            get {
                return ResourceManager.GetString("AddressDialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string AddressDialog_Edit {
            get {
                return ResourceManager.GetString("AddressDialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not usnderstand that address.  Can you try again?.
        /// </summary>
        internal static string AddressDialog_EnterAddressAgain {
            get {
                return ResourceManager.GetString("AddressDialog_EnterAddressAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was an invalid selection.
        /// </summary>
        internal static string MenuDialog_InvalidOption {
            get {
                return ResourceManager.GetString("MenuDialog_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are our featured items.
        /// </summary>
        internal static string MenuDialog_Prompt {
            get {
                return ResourceManager.GetString("MenuDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This one.
        /// </summary>
        internal static string MenuDialog_Select {
            get {
                return ResourceManager.GetString("MenuDialog_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item.
        /// </summary>
        internal static string PagedCarouselDialog_DefaultPrompt {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_DefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want more options?.
        /// </summary>
        internal static string PagedCarouselDialog_MoreOptions {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, please!.
        /// </summary>
        internal static string PagedCarouselDialog_ShowMe {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_ShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string RootDialog_Welcome_Directions {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t get that.
        /// </summary>
        internal static string RootDialog_Welcome_Error {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Hours.
        /// </summary>
        internal static string RootDialog_Welcome_Hours {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string RootDialog_Welcome_Menu {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Menu.
        /// </summary>
        internal static string RootDialog_Welcome_SeeMenu {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_SeeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best ingredients make the best tacos!.
        /// </summary>
        internal static string RootDialog_Welcome_Subtitle {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pete&apos;s Taco Shack!.
        /// </summary>
        internal static string RootDialog_Welcome_Title {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new address.
        /// </summary>
        internal static string SavedAddressDialog_AddNewAddress {
            get {
                return ResourceManager.GetString("SavedAddressDialog_AddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks!.
        /// </summary>
        internal static string SavedAddressDialog_NotThisTime {
            get {
                return ResourceManager.GetString("SavedAddressDialog_NotThisTime", resourceCulture);
            }
        }
    }
}
